### ISSUE TITLE
Issue data transaksi peminjaman

### ISSUE THREAD

**Issue by akumau-01** [ikhsan3adi/sistem-perpustakaan-qr-code#15]
Data transaksi peminjaman tidak bisa digunakan.
Ketika sudah saya pilih anggota peminjam dan buku pinjaman masih aman
gambar(1)
Tapi ketika saya mengklik tombol Konfirmasi
gambar(2)
Malah kembali ke halaman ini
gambar(3)

[issue.docx](https://github.com/user-attachments/files/16155178/issue.docx)

*Ngomong-ngomong saya tidak menggunakan scan QR

**Comment by ikhsan3adi** [comment]
Ini sudah saya fix di #11, mungkin karena menggunakan kode versi lama jadi bugnya masih ada

Solusinya timpa saja file `app/Controllers/Loans/LoansController.php` dengan kode file versi terbaru ini (direkomendasikan)

https://github.com/ikhsan3adi/sistem-perpustakaan-qr-code/blob/main/app%2FControllers%2FLoans%2FLoansController.php

Atau download ulang sourcecode terbaru
