### ISSUE TITLE
data peminjaman hilang

### ISSUE THREAD

**Issue by FAISHVL** [ikhsan3adi/sistem-perpustakaan-qr-code#8]
setelah saya memasukkan data pinjam baru data tersebut tidak masuk ke daftar pinjam

Uploading Dashboard - Google Chrome 2024-05-15 16-52-19.mp4…

**Comment by Naxsyl** [comment]
problem anda sama seperti saya

**Comment by ikhsan3adi** [comment]
Coba pakai code terbaru
